Transact packaging
hyperledger/transact pull request #110
Opened 2021-02-10 21:06 UTC by rbuysse

2021-02-10 21:18 UTC, agunde406 requested changes

2021-02-10 21:18 UTC, agunde406 commented on cli/Dockerfile
> +# -------------=== splinterd docker build ===-------------
Should say `transact CLI docker build`

2021-02-11 14:04 UTC, agunde406 approved these changes

2021-02-11 15:35 UTC, peterschwarz approved these changes

2021-02-11 16:49 UTC, merged