Update dependencies
hyperledger/transact pull request #123
Opened 2021-04-28 23:05 UTC by vaporos

Updates various dependencies, cleaning up the output of 'cargo outdated -R'.

2021-04-28 23:22 UTC, peterschwarz submitted a review, later dismissed

2021-05-27 13:33 UTC, agunde406 requested changes

2021-05-27 13:33 UTC, agunde406 commented on libtransact/Cargo.toml
> +hex = "0.4"
This should be in the next commit

2021-05-27 13:55 UTC, vaporos commented on libtransact/Cargo.toml
> +hex = "0.4"
fixed

2021-05-27 14:04 UTC, agunde406 approved these changes

2021-05-27 14:32 UTC, peterschwarz approved these changes

2021-05-27 15:02 UTC, merged