Command workload sabre executor example
hyperledger/transact pull request #156
Opened 2021-06-07 20:26 UTC by isabeltomb

This PR adds an example application to transact that uses the command workload to generate transactions and then runs them within Sabre

The application takes two command line arguments: the number of transactions to be run and the file path of the sabre-command wasm smart contract

**Testing:**

1. Get the sabre-command contract, the scar file containing the wasm contract can be found here: https://build.sawtooth.me/job/Transact-Hyperledger/job/transact/job/main/lastSuccessfulBuild/artifact/build/scar/ alternatively running `cargo build --target wasm32-unknown-unknown --release` in the examples/sabre_command directory will build the contract and it can be found in `target/wasm32-unknown-unknown/release/sabre-command.wasm` 
2. From the `examples/sabre_command_executor` directory run 
```
cargo run -- --transactions <number-of-transactions> --contract ../sabre_command/target/wasm32-unknown-unknown/release/sabre-command.wasm
```

2021-06-09 15:54 UTC, arsulegai submitted a review, later dismissed

2021-06-09 16:37 UTC, peterschwarz requested changes
Remove the expects

2021-06-09 16:37 UTC, peterschwarz commented on examples/sabre_command_executor/src/main.rs
> +                .expect("Unable to send batch result")
Remove the expects in this function - if this particular call fails, it should log an error.

2021-06-10 13:55 UTC, peterschwarz approved these changes

2021-06-10 19:46 UTC, vaporos approved these changes

2021-06-10 19:47 UTC, merged