SQL State pruning
hyperledger/transact pull request #175
Opened 2021-08-17 02:24 UTC by peterschwarz

2021-08-18 20:02 UTC, agunde406 requested changes

2021-08-18 20:02 UTC, agunde406 commented on libtransact/tests/state/merkle/mod.rs
> +/// successor with duplicate That changes one new leaf, followed by a second
typo -> "duplicate That changes"

2021-08-18 20:02 UTC, agunde406 commented on libtransact/tests/state/merkle/mod.rs
> +/// successor with duplicate That changes one new leaf, followed by a second
same typo

2021-08-18 20:41 UTC, peterschwarz commented on libtransact/src/state/merkle/sql/operations/get_leaves.rs
> -mod test {
Added back a set of simple tests - complex cases are handled by the integration tests. (Made note of this in the commit message now).

2021-08-18 20:42 UTC, peterschwarz commented on libtransact/tests/state/merkle/mod.rs
> +/// successor with duplicate That changes one new leaf, followed by a second
Fixed

2021-08-18 20:42 UTC, peterschwarz commented on libtransact/tests/state/merkle/mod.rs
> +/// successor with duplicate That changes one new leaf, followed by a second
Fixed

2021-08-18 20:42 UTC, peterschwarz commented on libtransact/src/state/merkle/sql/operations/prune_entries.rs
> + * Copyright 2021 Cargill Incorporated Licensed under the Apache License, Version 2.0 (the "License");
Fixed.

2021-08-19 16:09 UTC, agunde406 approved these changes

2021-08-19 16:59 UTC, shannynalayna approved these changes

2021-08-19 17:14 UTC, merged