Update MerkleRadixLeafReader rustdoc
hyperledger/transact pull request #180
Opened 2021-08-30 21:27 UTC by peterschwarz

This change updates the rustdoc for the `MerkleRadixLeafReader` trait and its associated error.

2021-09-01 13:48 UTC, agunde406 requested changes

2021-09-01 13:48 UTC, agunde406 commented on libtransact/src/state/merkle/error.rs
> +/// Error variants the may occur while reading Merkle Radix tree leaves.
the -> that

2021-09-01 19:31 UTC, peterschwarz commented on libtransact/src/state/merkle/error.rs
> +/// Error variants the may occur while reading Merkle Radix tree leaves.
Fixed

2021-09-02 14:21 UTC, agunde406 approved these changes

2021-09-02 19:20 UTC, rbuysse approved these changes

2021-09-02 19:27 UTC, merged