Add release notes for 0.3.8
hyperledger/transact pull request #185
Opened 2021-09-15 15:22 UTC by peterschwarz

Signed-off-by: Peter Schwarz <pschwarz@bitwise.io>

2021-09-15 18:53 UTC, vaporos approved these changes

2021-09-15 19:34 UTC, agunde406 requested changes

2021-09-15 19:34 UTC, agunde406 commented on RELEASE_NOTES.md
>  ## Changes in Transact 0.3.7
This need to be changed to 0.3.8

2021-09-15 19:37 UTC, peterschwarz commented on RELEASE_NOTES.md
>  ## Changes in Transact 0.3.7
Fixed

2021-09-15 19:40 UTC, agunde406 approved these changes

2021-09-22 14:36 UTC, vaporos approved these changes

2021-09-23 15:14 UTC, merged